### ISSUE TITLE
Update to GTDB 95? 

### ISSUE THREAD

**Issue by bsiranosian** [leylabmpi/Struo#8]
Love the ideas in this repo! Any plans to make a release available for GTDB 95?

**Comment by nick-youngblut** [comment]
We are working on that right now with a new algorithm that scales better. At least the kraken db should be available soon

**Comment by bsiranosian** [comment]
Excellent, glad to hear it.

**Comment by nick-youngblut** [comment]
I was waiting on the humann database to be complete, but I've gone ahead and uploaded all other data to the ftp site: http://ftp.tue.mpg.de/ebio/projects/struo/GTDB_release95/

The humann db will take a bit longer, since this is where the new algorithmic changes have occurred, and we need to make sure it's working properly.

**Comment by nick-youngblut** [comment]
See [Struo2](https://github.com/leylabmpi/Struo2)
